config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
  end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, presence: true
	validates :company, presence: true
	validates :url, presence:true, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  	@job = Job.page(params[:page]).per(25)
  end

  def new
  	@job = Job.new
  end

  def create
  	@job = Job.new(params.require(:job).permit(:title, :company, :url))
  	if @job.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<% @job.each do |kazi| %>
<div class="kazi">
<h2><%= link_to kazi.title, kazi.url %></h2>
<p><%= kazi.company%></p>
</div>
<% end %>
<%= link_to "Add a job", new_job_path %>

<p><%= paginate @job %></p>

app/views/jobs/new.html.erb
<h1>New Job</h1>
<%= simple_form_for @job do |form|%>
<%= form.input :title, label: "Job Title"%>
<%= form.input :company, label: "Company"%>
<%= form.input :url, label: "URL"%>
<%= form.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobsboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>